Repository TeamHARA/HARA_SERVER, pull requests merged in 2023-01, with the labels that each got.

#11 [FEAT] 고민글 전체 조회 구현 , API 테스트파일 생성
  package-lock.json
  prisma/schema.prisma
  src/constants/responseMessage.ts
  src/controller/index.ts
  src/controller/worryController.ts
  src/repository/categoryRepository.ts
  src/repository/index.ts
  src/repository/worryRepository.ts
  src/router/index.ts
  src/router/worryRouter.ts
  src/service/index.ts
  src/service/worryService.ts
  test/controller/worryController.spec.ts
Labels: 유진🐸, FEAT

#14 [CHORE] test 전에 prisma generate 실행
  package.json
Labels: CHORE

#15 [FEAT] 랜덤 답변 조회
  src/constants/responseMessage.ts
  src/controller/index.ts
  src/controller/randomController.ts
  src/interfaces/random/randomAnswerDTO.ts
  src/repository/index.ts
  src/repository/randomRepository.ts
  src/router/index.ts
  src/router/randomRouter.ts
  src/service/index.ts
  src/service/randomService.ts
  test/controller/randomController.ts
Labels: 승빈🦖, FEAT

#20 [FIX] 파일명 수정
  test/controller/randomController.spec.ts
Labels: 승빈🦖, HOTFIX

#16 [FEAT] 고민글 투표 생성
  src/controller/worryController.ts
  src/createWorryVoteDTO.ts
  src/repository/index.ts
  src/repository/voteRepository.ts
  src/repository/worryRepository.ts
  src/repository/worryWithRepository.ts
  src/router/worryRouter.ts
  src/service/index.ts
  src/service/voteService.ts
  src/service/worryService.ts
  src/service/worryWithService.ts
  test/controller/worryController.spec.ts
Labels: 유진🐸, FEAT

#21 [FEAT] 함께고민 생성
  prisma/schema.prisma
  src/constants/CreateAloneWorryDTO.ts
  src/controller/worryAloneController.ts
  src/controller/worryWithController.ts
  src/middlwares/index.ts
  src/middlwares/validation.ts
  src/repository/worryAloneRepository.ts
  src/router/worryAloneRouter.ts
  src/router/worryWithRouter.ts
Labels: 예린🐭, FEAT

#22 [FEAT] 함께고민 조회 기능
  src/controller/worryAloneController.ts
  src/controller/worryWithController.ts
  src/interfaces/worryWith/WorryWithPreview.ts
  src/repository/worryWithRepository.ts
  src/router/index.ts
  src/router/worryAloneRouter.ts
  src/router/worryWithRouter.ts
  src/service/worryWithService.ts
  test/controller/randomController.ts
  yarn.lock
Labels: 승빈🦖, FEAT

#26 [FEAT] 혼자 고민 목록 조회
  src/constants/responseMessage.ts
  src/controller/worryAloneController.ts
  src/controller/worryWithController.ts
  src/interfaces/worryAlone/WorryAlonePreview.ts
  src/repository/worryAloneRepository.ts
  src/router/worryAloneRouter.ts
  src/service/worryAloneService.ts
Labels: 승빈🦖, FEAT

#27 [FEAT] 고민글 전체 조회 수정
  src/constants/CreateAloneWorryDTO.ts
  src/constants/dateFormat.ts
  src/controller/worryController.ts
  src/repository/voteRepository.ts
  src/repository/withOptionRepository.ts
  src/repository/worryWithRepository.ts
  src/router/worryRouter.ts
  src/service/voteService.ts
  src/service/worryWithService.ts
  src/worryVoteDTO.ts
Labels: 유진🐸, CHORE

#29 [FEAT] 혼자 고민글 최종 결정하기 API
  src/constants/responseMessage.ts
  src/controller/index.ts
  src/controller/worryAloneController.ts
  src/interfaces/worryAlone/ChooseAloneWorryDTO.ts
  src/repository/aloneOptionRepository.ts
  src/repository/worryAloneRepository.ts
  src/repository/worryWithRepository.ts
  src/router/worryAloneRouter.ts
  src/service/worryAloneService.ts
  src/service/worryWithService.ts
  test/controller/worryAloneContoller.spec.ts
  test/controller/worryWithController.spec.ts
Labels: 가영🐰, FEAT

#23 [FEAT] 함께고민글 상세조회
  prisma/schema.prisma
  src/controller/worryAloneController.ts
  src/controller/worryWithController.ts
  src/repository/withOptionRepository.ts
  src/repository/worryWithRepository.ts
  src/router/worryWithRouter.ts
  src/service/worryWithService.ts
Labels: 예린🐭, FEAT

#33 [FEAT] Github Actions CI 등록
  .github/workflows/deploy.yml
Labels: 유진🐸, FEAT

#34 [FEAT] 혼자고민 상세조회
  src/controller/worryAloneController.ts
  src/repository/aloneOptionRepository.ts
  src/repository/worryAloneRepository.ts
  src/router/worryAloneRouter.ts
  src/service/worryAloneService.ts
Labels: 예린🐭, FEAT

#37 [CHORE] 노드버전 변경
  .github/workflows/deploy.yml
Labels: 유진🐸, CHORE

#45 [CHORE] 스크립트 코드 수정
  .github/workflows/deploy.yml
  scripts/after-deploy.sh
Labels: 유진🐸, CHORE

#51 [FEAT] 댓글 생성
  prisma/schema.prisma
  src/common/utils/calculatePercentage.ts
  src/constants/responseMessage.ts
  src/controller/worryAloneController.ts
  src/controller/worryWithController.ts
  src/interfaces/worryWith/CreateCommentDTO.ts
  src/repository/commentRepository.ts
  src/repository/withOptionRepository.ts
  src/repository/worryWithRepository.ts
  src/service/commentService.ts
  src/service/worryWithService.ts
  test/controller/worryAloneContoller.spec.ts
  test/controller/worryController.spec.ts
  test/sum.test.js
  test/sum.ts
Labels: 예린🐭, FEAT

#52 [HOTFIX] 메인 충돌 수정 & 더미데이터 추가한 것 돌아가는지 확인
  src/interfaces/worryAlone/WorryAlonePreview.ts
Labels: 유진🐸, HOTFIX

#54 [CHORE] 홈화면 선택지 옵션값 response 추가
  src/repository/voteRepository.ts
  src/service/worryWithService.ts
Labels: 유진🐸, CHORE

#55 [FEAT] 혼자 고민글 삭제
  prisma/schema.prisma
  src/constants/responseMessage.ts
  src/controller/worryAloneController.ts
  src/repository/worryAloneRepository.ts
  src/router/worryAloneRouter.ts
  src/service/worryAloneService.ts
Labels: 유진🐸, FEAT

#57 [FIX] 빌드파일 수정
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: 유진🐸, CHORE

#58 [FEAT] 함께 고민글 삭제
  src/controller/worryWithController.ts
  src/repository/worryAloneRepository.ts
  src/repository/worryWithRepository.ts
  src/router/worryAloneRouter.ts
  src/router/worryWithRouter.ts
  src/service/worryAloneService.ts
  src/service/worryWithService.ts
Labels: 유진🐸, FEAT

#60 [HOTFIX] 함께 고민글 생성/고민 작성하기 오류사항 수정
  src/router/worryWithRouter.ts
Labels: 유진🐸, HOTFIX

#61 [FIX] content에서 title전송으로 변경
  src/interfaces/worryAlone/WorryAlonePreview.ts
  src/interfaces/worryWith/WorryWithPreview.ts
  src/repository/worryAloneRepository.ts
  src/repository/worryWithRepository.ts
Labels: 승빈🦖, HOTFIX

#63 [FEAT] slack webhook연결하기
  .github/workflows/deploy.yml
  package.json
  src/common/error/handler.ts
  src/config/index.ts
  src/controller/worryWithController.ts
  src/index.ts
  src/middlwares/errorSender.ts
  src/middlwares/slackAlarm.ts
  src/middlwares/validation.ts
  yarn.lock
Labels: 승빈🦖, FEAT

#70 [TEST] 함께 고민, 혼자 고민 목록 조회 TESTCODE작성
  test/controller/worryAloneContoller.spec.ts
  test/controller/worryWithController.spec.ts
Labels: 승빈🦖, FEAT

#71 [CHORE] 투표하기데이터 수정, 홈화면 전체 조회 수정
  src/controller/worryController.ts
  src/repository/voteRepository.ts
  src/repository/withOptionRepository.ts
  src/repository/worryWithRepository.ts
  src/service/voteService.ts
  src/service/worryAloneService.ts
  src/service/worryWithService.ts
  test/controller/worryController.spec.ts
Labels: 유진🐸, CHORE

#73 [CHORE] 정렬조건 수정, 투표하기 오류 수정
  src/repository/aloneOptionRepository.ts
  src/repository/categoryRepository.ts
  src/repository/commentRepository.ts
  src/repository/randomRepository.ts
  src/repository/voteRepository.ts
  src/repository/worryAloneRepository.ts
  src/repository/worryWithRepository.ts
  src/service/voteService.ts
Labels: 유진🐸, CHORE

#76 [CHORE] isVoted 로직 수정
  src/controller/worryController.ts
  src/service/voteService.ts
  src/service/worryWithService.ts
Labels: 유진🐸, CHORE

#78 [CHORE] isVoted 수정, 이미 투표한 사람 투표 못하게 추가
  src/repository/voteRepository.ts
  src/service/voteService.ts
  src/service/worryWithService.ts
Labels: 유진🐸, CHORE

#80 [CHORE] README 수정
  README.md
Labels: 유진🐸, CHORE

#88 [CHORE] Readme 이미지 추가
  README.md
Labels: 유진🐸, CHORE

#86 [CHORE] 테스트 코드 작성
  src/controller/worryWithController.ts
  src/service/voteService.ts
  test/controller/worryController.spec.ts
Labels: 유진🐸, CHORE

#87 [FIX] createWorryVote 에서 returnData 수정
  src/service/voteService.ts
  src/service/worryWithService.ts
Labels: 예린🐭, FIX

#89 [HOTFIX] 테스트 코드 수정
  test/controller/worryController.spec.ts
Labels: 유진🐸, HOTFIX
